#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v24
# autospec commit: a88ffdc
#
Name     : vc-intrinsics
Version  : 0.22.1
Release  : 2
URL      : https://github.com/intel/vc-intrinsics/archive/v0.22.1/vc-intrinsics-0.22.1.tar.gz
Source0  : https://github.com/intel/vc-intrinsics/archive/v0.22.1/vc-intrinsics-0.22.1.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: vc-intrinsics-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : libedit-dev
BuildRequires : libffi-dev
BuildRequires : libxml2-dev
BuildRequires : llvm-dev
BuildRequires : python3
BuildRequires : zlib-dev
BuildRequires : zstd-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
<!---======================= begin_copyright_notice ============================

%package dev
Summary: dev components for the vc-intrinsics package.
Group: Development
Provides: vc-intrinsics-devel = %{version}-%{release}
Requires: vc-intrinsics = %{version}-%{release}

%description dev
dev components for the vc-intrinsics package.


%package license
Summary: license components for the vc-intrinsics package.
Group: Default

%description license
license components for the vc-intrinsics package.


%prep
%setup -q -n vc-intrinsics-0.22.1
cd %{_builddir}/vc-intrinsics-0.22.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1744825162
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DLLVM_DIR=/usr/lib64  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1744825162
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/vc-intrinsics
cp %{_builddir}/vc-intrinsics-%{version}/LICENSE.md %{buildroot}/usr/share/package-licenses/vc-intrinsics/723eea2469244a92b3e3461b79c3e848ce058cc6 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/llvm/GenXIntrinsics/GenXIntrOpts.h
/usr/include/llvm/GenXIntrinsics/GenXIntrinsicDescription.gen
/usr/include/llvm/GenXIntrinsics/GenXIntrinsicInst.h
/usr/include/llvm/GenXIntrinsics/GenXIntrinsics.h
/usr/include/llvm/GenXIntrinsics/GenXMetadata.h
/usr/include/llvm/GenXIntrinsics/GenXSPIRVReaderAdaptor.h
/usr/include/llvm/GenXIntrinsics/GenXSPIRVWriterAdaptor.h
/usr/include/llvm/GenXIntrinsics/GenXSimdCFLowering.h
/usr/include/llvm/GenXIntrinsics/GenXVersion.h
/usr/lib64/cmake/LLVMGenXIntrinsics/LLVMGenXIntrinsicsConfig-relwithdebinfo.cmake
/usr/lib64/cmake/LLVMGenXIntrinsics/LLVMGenXIntrinsicsConfig.cmake
/usr/lib64/cmake/VCIntrinsics20/VCIntrinsics20Config-relwithdebinfo.cmake
/usr/lib64/cmake/VCIntrinsics20/VCIntrinsics20Config.cmake
/usr/lib64/libLLVMGenXIntrinsics.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/vc-intrinsics/723eea2469244a92b3e3461b79c3e848ce058cc6
